// Generated by CoffeeScript 1.3.3
/*
@author Tantaman
*/

define(["./Component", "common/FileUtils"], function(Component, FileUtils) {
  return Component.extend({
    initialize: function() {
      var videoType;
      Component.prototype.initialize.apply(this, arguments);
      this.set("type", "Video");
      videoType = FileUtils.type(FileUtils.extension(this.get('src')));
      //alert(this.get('id'));
      this.set("videoShape",this.get('id'));
      this.set("style",this.get('style'));
      return this.set("videoType", videoType);
    },
    constructor: function Video() {
			Component.prototype.constructor.apply(this, arguments);
		}
  });
});
